spring:
  profiles:
    group:
      local :
        - jwt
        - oauth
        - local
      active: local
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true